name: Build and Push Docker Image to Docker Hub

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: login to docker registry
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}

        - name: build and push rair-node docker image to registry
          uses: docker/build-push-action@v5
          with:
            context: rair-node/
            push: true
            tags: rairprotocol/rair-node:latest

        - name: build and push rair-front docker image to registry
          uses: docker/build-push-action@v5
          with:
            context: rair-front/
            file: rair-front/Dockerfile.prod
            push: true
            tags: rairprotocol/rair-front:latest
            
        - name: build and push rair-stream docker image to registry
          uses: docker/build-push-action@v5
          with:
            context: rair-stream/
            push: true
            tags: rairprotocol/rair-stream:latest

        - name: build and push rair-sync docker image to registry
          uses: docker/build-push-action@v5
          with:
            context: rair-sync/
            push: true
            tags: rairprotocol/rair-sync:latest

